### ISSUE TITLE
Logo Design - Figma

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-frontend#5]

**Comment by hatoriMain** [comment]
# Logo Design
The Trophy one is the first version of our Logo design.
if you have another preference, please comment!
@mokumoku-lovers/moku-back @mokumoku-lovers/moku-front 
<div align = "center">
<img src = "https://user-images.githubusercontent.com/51203739/126584399-b45b033d-1d4e-4857-93db-c41b26921e2b.png", width = 600px>
<div>

**Comment by JiahuiChen99** [comment]
These are good looking designs 👀 
I like the one that has the trophy icon on it too, but what if you added the `+` sign in that one 🧐

**Comment by hatoriMain** [comment]
I guess the `+` sign may cause some misunderstanding because it may refer to "MokuPlus"? So I didn't add it to other designs! But if you think the one with `+` is cooler, I can try later.

And I'm sorry that some of the designs are still at the "inspiration" stage, they are not completed except the Trophy one...I guess it may help us to come up with some new designs so they are kept.

**Comment by JiahuiChen99** [comment]
Yeah, MokuPlus 😂
It's also fine without the `+`. So up to you and the team to decide 👍 
The trophy one is my first choice, the second one would be the one in the left side of the 🏆

**Comment by hatoriMain** [comment]
![image](https://user-images.githubusercontent.com/51203739/126902113-38f4ce31-9b62-48de-b8c9-c8597a369b54.png)
Since the result is tied I will refer to other members' comments to make some new combined version designs.

**Comment by JiahuiChen99** [comment]
👀 Looking forward to seeing the final design of our project logo わくわく~
